### ISSUE TITLE
Group Search Error

### ISSUE THREAD

**Issue by gjmscc** [OfficeDev/microsoft-teams-company-communicator-app#222]
App Version v2.11

Company Communicator App errors when searching for groups

**Steps to recreate issue**

Create a message and select send to a group etc. 
![image](https://user-images.githubusercontent.com/70025918/96690984-420db880-137c-11eb-9638-3cb05501ce6e.png)

Errors is thrown after typing more than 3 chars. 
![image](https://user-images.githubusercontent.com/70025918/96691181-7b462880-137c-11eb-82ec-797baa760719.png)

**Application Analytics Errors** 

**Request** 
GET /api/groupdata/search/All
**Error**
Value cannot be null. (Parameter 'collection') System.ArgumentNullException at lambda_method
**Trace:** 
System.ArgumentNullException: Value cannot be null. (Parameter 'collection')
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at Microsoft.Teams.Apps.CompanyCommunicator.Common.Services.MicrosoftGraph.Groups.GroupsService.SearchAsync(String query) in D:\home\site\repository\Source\Microsoft.Teams.Apps.CompanyCommunicator.Common\Services\MicrosoftGraph\Groups\GroupsService.cs:line 83
   at Microsoft.Teams.Apps.CompanyCommunicator.Controllers.GroupDataController.SearchAsync(String query) in D:\home\site\repository\Source\Microsoft.Teams.Apps.CompanyCommunicator\Controllers\GroupDataController.cs:line 66
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

App Registration has all the correct permissions to the graph api etc.

**Comment by bungleweed** [comment]
Does this fix this? https://github.com/OfficeDev/microsoft-teams-company-communicator-app/pull/195

**Comment by gjmscc** [comment]
commit id https://github.com/OfficeDev/microsoft-teams-company-communicator-app/commit/df981055e152123f16c85a4d7b1fb650036c6d6b resolved this issue. Many Thanks 👍
